<?php

/**
 * Cronnables
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property Groups $Groups
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Cronnables extends BaseCronnables {
  public function assignDefaultValues($overwrite = false) {
    parent::assignDefaultValues($overwrite);
    
    $this->added = date("Y-m-d H:i:s");
    $this->attempts = 0;
  }
  
  public function setUp() {
    parent::setUp();
    $this->hasOne('Groups', array(
        'local' => 'group_id',
        'foreign' => 'id'));
  }
}