<?php

/**
 * Groups
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property Doctrine_Collection $Cronnables
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Groups extends BaseGroups {

  public function assignDefaultValues($overwrite = false) {
    parent::assignDefaultValues($overwrite);
    
    $this->added = date("Y-m-d H:i:s");
  }
  
  public function setUp() {
    parent::setUp();
    $this->hasMany('Cronnables', array(
        'local' => 'id',
        'foreign' => 'group_id'));
  }

}